#pragma once
#include "Typedef.h"

enum Emotion : uint8_t {
    EMOTION_NEUTRAL,
    EMOTION_IRATE,
    EMOTION_HOSTILE,
    EMOTION_FRIENDLY,
    EMOTION_LOVE,
    EMOTION_ANXIOUS,
    //EMOTION_DEPRESSED,
    EMOTION_SUSPICIOUS,
	EMOTION_BESERK,
	EMOTION_TERRIFIED
};