#pragma once
#include <cstdint>

enum GenerationMode : uint8_t {
	STABLE_POWER = 0,
	SEMISTABLE_POWER = 1,
	UNSTABLE_POWER = 2,
	CIVIL_WAR = 3,
	STATELESS = 4,
	ABSOLUTE_POWER = 5,
	DECLINING_POWER = 6,
	BALANCED_POWERS = 7
};

enum AutonomyLevel : uint8_t {
	NO_AUTONOMY = 0,
	DEPOTISM = 1,
	HEIRARCHY = 2,
	DECENTRALISED = 3,
	ANARCHIST = 4
};

enum GroupType : uint8_t {
	POLITICAL_GROUP = 0,
	STATE = 1,
	INSTITUTION = 2,
	BUSINESS = 3,
	GANG = 4,
	CULTURAL_GROUP = 5,
	DIRECT_ACTION = 6
};

enum PowerClass : uint8_t {
	AUTHORITY_ALPHA = 0,
	AUTHORITY_CHALLENGER = 1,
	AUTHORTIY_RIGHTARM = 2,
	AUTHORITY_HIGH = 3,
	AUTHORITY_MEDIUM = 4,
	AUTHORITY_LOW = 5,
	AUTHORITY_VERYLOW = 6
};