#pragma once
#include <SFML\Graphics.hpp>
#include "Typedef.h"
#include "Freerun.h"

const uint8_t MAX_WIDTH = 1000;
const uint8_t MAX_HEIGHT = 1000;

enum Terrain : uint8_t {
	FLAT_GROUND,
	SLIGHT_INCLINE,
	DRASTIC_INCLINE,
	WALL_FULL,
	WALL_PARTIAL,
	DOORWAY,
	WINDOW_FULL,
	WINDOW_PARTIAL,
	WATER
};

const suint MAX_ACTIVE_TERRAINS = 16;
enum TerrainGraphic : uint8_t {
	FLOOR_DEFAULT = 0,
	FLOOR_CARPET = 1,
	FLOOR_CONCRETE = 2,
	FLOOR_DIRT = 3,
	FLOOR_FRESHWATER = 4,
	FLOOR_GRASS = 5,
	FLOOR_ROOFING_FLAT = 6,
	FLOOR_ROOFING_PRECARIOUS = 7,
	FLOOR_SALTWATER = 8,
	FLOOR_SAND = 9,
	FLOOR_WOOD = 10
};

enum Climate : uint8_t {
	ARCTIC,
	TUNDRA,
	TEMPERATE_COLD,
	TEMPERATE_WARM,
	PLAINS,
	TROPICAL,
	ARID,
	DESERT
};

enum FeaturePresence : uint8_t {
	EVERYWHERE,
	ABUNDANT,
	LARGE_AREA,
	SPARSE,
	SMALL_AREA,
	SINGULAR,
	NO_PRESENCE
};