#pragma once

//TODO: disabilities?
enum Trait : uint8_t {
	TRAIT_NULL,

	//mental conditions (4)
	//TRAIT_MENTAL_PSYCOPATHIC,
	TRAIT_MENTAL_DEPRESSION,
	TRAIT_MENTAL_ANXIETY,
	TRAIT_MENTAL_AUTISM,
	TRAIT_MENTAL_PTSD,
	//TRAIT_MENTAL_NAPOLEON,
	//TRAIT_MENTAL_ANGER,
	//TRAIT_MENTAL_ADDICTION, //TODO: how to specify what?
	//TRAIT_MENTAL_MESSIAH,
	//TRAIT_MENTAL_NARCASSIST,

	//injury / imparement (1)
	TRAIT_INJURY_MEMORY,
	//TRAIT_INJURY_MOVEMENT,
	//TRAIT_INJURY_JUDGEMENT,
	//TRAIT_INJURY_WEAKNESS,
	//TRAIT_INJURY_DISTRACTION,

	//personality (3)
	TRAIT_PERSON_AGGRESSIVE,
	//TRAIT_PERSON_SYMPATHETIC,
	//TRAIT_PERSON_RUDE,
	//TRAIT_PERSON_JUDGEMENTAL,
	//TRAIT_PERSON_GOAT,
	TRAIT_PERSON_BRAVE,
	TRAIT_PERSON_COWARD,

	//vulnerabilities (3)
	TRAIT_VULN_BLACKMAIL,
	TRAIT_VULN_COERCE,
	TRAIT_VULN_BRIBE
};

enum TraitType : uint8_t {
	TRAIT_TYPE_NULL,
	TRAIT_TYPE_MENTAL,
	TRAIT_TYPE_INJURY,
	TRAIT_TYPE_PERSONALITY,
	TRAIT_TYPE_VULNERABILITY
};